version: '3'

services:
  javaapp:
    image: docker.io/satish736/abc:latest
    ports:
      - 8090:8080
    networks:
      - isolated
  mysqlapp:
    image: docker.io/satish736/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret 
    ports:
      - 3311:3306
    networks:
      - isolated

networks: 
  isolated:
    driver: bridge
